### ISSUE TITLE
Python Conversion via Website doesnt work

### ISSUE THREAD

**Issue by geekyhawkes** [probonopd/PoorMakers_IR_Receiver#2]
Hello;

I have the Arduino sketch working and have collected data without issue but the Python Script doesnt work:

File "analyze)using)irdb.py", line 21 print line.strip().replace('"',"").replace(',',"")

SyntaxError: invalid syntax

Can you provide some help with this please? 

I am using Python 3.4.3 in windows.

**Comment by probonopd** [comment]
Try with Python 2

**Comment by geekyhawkes** [comment]
More success with Python 2, but I am having an issue with the ardunio.run()

Traceback (most recent call last):
  File "D:\Arduino\IRDBGrabber\analyze_using_irdb.py", line 49, in <module>
    arduino.run()
  File "D:\Arduino\IRDBGrabber\analyze_using_irdb.py", line 40, in run
    inp, outp, err = select.select([sys.stdin, self.ser], [], [], .2)
UnsupportedOperation: fileno

I have the sketch loaded and using the ardunio IDE I can see raw output from serial monitor.

**Comment by probonopd** [comment]
Can you please post the code that gives you the 500 error?

**Comment by geekyhawkes** [comment]
Sure:

Grabbed using your sketch the OFF button on my remote generates this:
, +4290761996, +4290748544, +4290747408, +4290746304, +4290745172, +4290744044, +4290742940, +4290741812, +4290740680, +4290739576, +4290737316, +4290735084, +4290732848, +4290730588, +4290729480, +4290727224, +4290724988, +4290722756, +4290721624, +4290719392, +4290718256, +4290717128, +4290716024, +4290714896, +4290713764, +4290712660, +4290710404, +4290709296, +4290707040, +4290704804, +4290702568, +4290700312, +42906980764290695844
Modulation Period: 2233125 (nano seconds)
Modulation Frequency: 447 (Hz)

Using Sketch Below the OFF button gives:
Decoded NEC(1): Value:F740BF (32 bits)
Raw samples(68): Gap:1804
  Head: m8750  s4550
0:m450 s650	1:m500 s600		 2:m500 s650	3:m450 s650		 
4:m450 s650	5:m500 s600		 6:m500 s650	7:m450 s600		 
8:m500 s1750	9:m500 s1700		 10:m500 s1750	11:m450 s1750		 
12:m500 s600	13:m500 s1750		 14:m450 s1750	15:m500 s1700		 

16:m500 s650	17:m450 s1750		 18:m500 s600	19:m500 s650		 
20:m450 s650	21:m500 s600		 22:m450 s650	23:m500 s600		 
24:m500 s1750	25:m450 s650		 26:m500 s1750	27:m450 s1750		 
28:m450 s1750	29:m500 s1750		 30:m450 s1750	31:m450 s1750		 

32:m500
Extent=65950
Mark  min:450	 max:500
Space min:600	 max:1750



For extra sample the ON button:
, +4240913216, +4240899764, +4240898628, +4240897524, +4240896396, +4240895264, +4240894160, +4240893032, +4240891896, +4240890796, +4240888540, +4240886304, +4240884072, +4240881812, +4240880704, +4240878448, +4240876212, +4240873976, +4240871720, +4240869484, +4240868348, +4240867248, +4240866116, +4240864988, +4240863884, +4240862756, +4240861624, +4240860520, +4240858264, +4240856028, +4240853796, +4240851536, +42408493004240847064
Modulation Period: 2237062 (nano seconds)
Modulation Frequency: 447 (Hz)

And using the sketch below the ON button generates:
Decoded NEC(1): Value:F7C03F (32 bits)
Raw samples(68): Gap:55674
  Head: m8800  s4550
0:m450 s650	1:m450 s650		 2:m500 s600	3:m500 s650		 
4:m450 s600	5:m500 s650		 6:m450 s650	7:m450 s650		 
8:m500 s1750	9:m450 s1750		 10:m450 s1750	11:m500 s1750		 
12:m450 s650	13:m500 s1700		 14:m500 s1750	15:m450 s1750		 

16:m500 s1750	17:m450 s1750		 18:m450 s650	19:m500 s600		 
20:m500 s650	21:m450 s650		 22:m450 s650	23:m500 s600		 
24:m500 s650	25:m450 s600		 26:m500 s1750	27:m500 s1700		 
28:m500 s1750	29:m450 s1750		 30:m500 s1750	31:m450 s1750		 

32:m500
Extent=66000
Mark  min:450	 max:500
Space min:600	 max:1750


Sketch using IRLib in case its helpful:
#include <IRLib.h>

//Create a receiver object to listen on pin 11
IRrecv My_Receiver(11);

//Create a decoder object
IRdecode My_Decoder;

void setup()
{
  Serial.begin(9600);
  My_Receiver.enableIRIn(); // Start the receiver
}

void loop() {
//Continuously look for results. When you have them pass them to the decoder
  if (My_Receiver.GetResults(&My_Decoder)) {
    My_Decoder.decode();    //Decode the data
    My_Decoder.DumpResults(); //Show the results on serial monitor
    My_Receiver.resume();     //Restart the receiver
  }
}

Thanks for your help! Hopefully I can get to the stage of grabbing my full remote and getting the pronto hex codes for it.

**Comment by probonopd** [comment]
The 42409... codes are not correct. Whicih type of Arduino are you using?

**Comment by geekyhawkes** [comment]
Its an Arduino Uno

**Comment by probonopd** [comment]
What kind of device does the IR remote belong to?

**Comment by geekyhawkes** [comment]
It is a remote control for changing the LED colour, brightness, fade for PC cases:
http://www.satechi.net/index.php/computer/rgb-led-light-strip

I have tried the capture with 2 different Arduino Unos and get the same results.  I know I am using a good IR Receiver as I am using the one from the LED kit

**Comment by probonopd** [comment]
Try
```
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C
```

**Comment by geekyhawkes** [comment]
I tried this code but nothing happened.  I captured the code back with the ardinuo and got this:
, +42868489604286844836
Modulation Period: 31562 (nano seconds)
Modulation Frequency: 31683 (Hz)

**Comment by probonopd** [comment]
Then the code on your Arduino is not working properly for whatever reason. The most obvious reason would be that the distance between sender LED and receiver LED is too high. Make them so close that they actually touch each other and are precisely aligned.

**Comment by geekyhawkes** [comment]
ok, so the sketch is as your site here - with the IR Blaster touching the LED receiver on my arduino then your Pronto Hex gives me this result:

Pronto Hex:
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 05F7 015B 0057 0016 0E6C

Sending code from the android app im using is:

power pushed, sending 38380,347,173,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,65,22,65,22,65,22,65,22,65,22,65,22,65,22,65,22,65,22,65,22,22,22,22,22,65,22,22,22,22,22,22,22,22,22,22,22,65,22,65,22,22,22,65,22,65,22,65,22,1527,347,87,22,3692

Capture from the IR Receiver with my phone touching it gives:
, +42724489284272444776
Modulation Period: 53625 (nano seconds)
Modulation Frequency: 18648 (Hz)

, +42707580444270753916
Modulation Period: 34437 (nano seconds)
Modulation Frequency: 29038 (Hz)

, +42699249444269920816
Modulation Period: 31125 (nano seconds)
Modulation Frequency: 32128 (Hz)

, +42691110924269106964
Modulation Period: 33937 (nano seconds)
Modulation Frequency: 29466 (Hz)

**Comment by probonopd** [comment]
You got that ```0000 006C 0022```code using the receiver LED on your Arduino? Hey, that's progress. You get exactly the Pronto Hex I had guessed by just looking at the picture of your remote control :-)
So that means that you have successfully decoded your remote's code.

It also means that the same circuit is not able to decode what you phone sends. Are you sure your phone is sending the correct codes? Which software are you using?

**Comment by geekyhawkes** [comment]
I should have been more clear, The pronto hex was just a copy paste of your code, I havent seen that out of my arduino.  I am using my own software written for android based on this code https://github.com/fishjord/IRDARemote

I might be a total Idiot!  How important are the resistors on the IR Rx?  I havent actually connected any resistors yet!

**Comment by probonopd** [comment]
Well the `38380,347,173, ...` seems to be the correct translation of `0000 006C 0022 ...`. Are you sure the app you wrote sends correct pulses? Did you verify, e.g., with a TSOP connected to an oscilloscope or logic analyzer? Can you control actual devices with it?

**Comment by geekyhawkes** [comment]
Could you post several pronto hex based on the same remote I posted earlier so I can try them? Im short of hardware this end and dont have an oscilloscope or any kind of logic analyzer (hence my arduino approach).  

The control board for the IR Rx supplied with the LEDs is run by this controller:
http://www.atmel.com/images/doc0180.pdf

I cant find out much else. Thanks for your help so far!
